seed: 0
learning_rate: 3e-4
entropy_cost: 1e-2
num_envs: 2048
batch_size: 1024
num_update_epochs: 4
num_minibatches: 32
unroll_length: 5
number_of_cell_types: 64
is_weight_sharing: false
clipping_val: 0.3
within_lifetime_clipping_val: 0.3
within_lifetime_learning_rate: 3e-4
env_name: "ant"
complexity_cost: 0
episode_length: 1000
device: "cuda"
num_timesteps: 100000000
eval_frequency: 20
reward_scaling: 0.1
discounting: 0.97
