seed: 0
learning_rate: 3e-4
entropy_cost: 1e-3
num_envs: 2048
batch_size: 512
num_update_epochs: 8
num_minibatches: 32
unroll_length: 20
number_of_cell_types: 64
is_weight_sharing: false
clipping_val: 0.3
within_lifetime_clipping_val: 0.3
within_lifetime_learning_rate: 3e-4
env_name: "halfcheetah"
complexity_cost: 0.0001
episode_length: 1000
device: "cuda"
num_timesteps: 100000000
eval_frequency: 40
reward_scaling: 1.0
discounting: 0.95
hidden_size: 64
hidden_size: 128
SOTA_performance: 4838
min_performance: -724
eval_population: False
samples_to_take: 3
networks_to_sample: 3
